name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Container Jar
        working-directory: ./naming-server
        run: mvn clean package -DskipTests
        
      - name: Build API Gateway Container Jar
        working-directory: ./api-gateway
        run: mvn clean package -DskipTests
        
      - name: Build Cambio Microservice Jar
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Microservice Jar
        working-directory: ./book-service
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:latest ${{ secrets.DOCKER_USERNAME }}/naming-server:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest ${{ secrets.DOCKER_USERNAME }}/cambio-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:latest ${{ secrets.DOCKER_USERNAME }}/book-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:latest
